name: Build

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
      with:
        submodules: recursive
    - name: Run apt update
      run: sudo apt update
    - name: Install LibELF
      run: sudo apt install -y libelf-dev
    - name: Install LibConfig
      run: sudo apt install -y libconfig-dev 
    - name: Install LLVM
      run: sudo apt install -y llvm
    - name: Install LibXDP Depedencies
      run: sudo apt install -y libpcap-dev m4 gcc-multilib linux-tools-$(uname -r)
    - name: Build LibXDP.
      run: make libxdp
    - name: Install LibXDP.
      run: sudo make libxdp_install
    - name: Make project
      run: make
    - name: Install project
      run: sudo make install